### ISSUE TITLE
some adjustments for Matlab R2020a and bin_x issue

### ISSUE THREAD

**Issue by Ocartapanis** [nickmckay/Temperature12k#3]
Dear Nick, 
I’m currently trying to make my way into the Temp12k scripts  and found a few issues (which might only concern my Matlab version R2020b, not sure about that) with the createAllFigures.m function. You’ll find a description below.
But I’m also annoyed by what could be more problematic: there are 2 different functions called bin_x in the folder. They basically look similar but I'm not 100% they are exactly equivalent. One can deal with four outputs the other has only 3 (but that could be easily corrected) only if they actually do the same thing! I suppose one comes from LiPDverse and one was slightly modified for Temp12k. 
Any clue?
Best, Olivier

% error spotted in Temp12k-master functions 
% I'm using Matlab R2020a on mac

% In Fig2.m 

% L232: wrong linestyle 
% gridm('glinestyle','.','plinelocation',20) should be gridm('glinestyle',':','plinelocation',20)
% L234: Wrong longitude name but it plot lines between dots... which we
% don't want i think... Put a % in front of L234
% L234: linem(lat,long,'Color','k','LineWidth',2); should be linem(lat,lon,'Color','k','LineWidth',2);

% in Fig4.m
% L89 calls for bin_x but there are 2 different conflicting versions of bin_x

**Comment by nickmckay** [comment]
Thanks Olivier,

I changed the linestyle on L232, which didn't seem to break it on my older version of matlab. 

For 234, I think that "long" is actually the correct variable - it comes in on "load coast" on line 234

For bin_x, the right version is the on in the DataDescriptor directory. I changed the one in the analysis directory to match this. I kept both as I want both of those codebases to stand alone. 

Thanks for looking into this, let me know if you run into any other issues with this or the Matlab utilities.

**Comment by Ocartapanis** [comment]
Dear Nick, 
Thank you for your answers, I’ll check them tomorrow. I wasn’t sure the other version of bin_x wasn’t used in another script.
Another thing I noted:
% In Fig5.m
% wrong referencement for MarineSediment. 
% L12: mn = find(strncmpi('MarineSediment',{TS.archiveType}',1)); %index all marine archives
% this actually refer to MarineSediment AND Midden (some of Midden archives
% are in the middle of the USA)
% L12 should rather be mn = find(strcmp('MarineSediment',{TS.archiveType}')); %index all marine archives

**Comment by Ocartapanis** [comment]
Dear Nick, 
coast.mat isn’t in the folder, explaining why it broke my code. I actually do have one coast.mat with likely a different format from yours… coast.lon and coast.lat. solved for me but coast.mat missing for others.
best
